// 
// Decompiled by Procyon v0.5.36
// 

package Main;

public enum NotificationMessage
{
    SCENE_CHANGED_NOTIFICATION, 
    SIZE_CHANGED_NOTIFICATION, 
    UPDATE_GUI_NOTIFICATION, 
    AUTO_FADER_ACTIVATED_NOTIFICATION, 
    TIMER_UPDATE_NOTIFICATION, 
    SCENE_LIST_CHANGED_NOTIFICATION, 
    PLAY_LIST_CHANGED_NOTIFICATION, 
    FADER_VALUE_UPDATE_NOTIFICATION, 
    FADER_REACHED_ENDPOSITION_NOTIFICATION, 
    MASTER_DIMMER_CHANGED_NOTIFICATION, 
    BLACK_OUT_FINSHED_NOTIFICATION;
}
